# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
